@auth-url=http://127.0.0.1:8080/librarian-auth
@librarian-url=http://127.0.0.1:8080/librarians
@book-url=http://localhost:8080/books 
@bookrequest-url=http://127.0.0.1:8080/bookrequests
@borrow-url=http://127.0.0.1:8080/borrowrecords
@auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiTElCUkFSSUFOIiwidXNlcklkIjoxMDEsInN1YiI6IkxfcmFobWFuIiwiaWF0IjoxNzQ2Njk0NzA2LCJleHAiOjE3NDY3ODExMDZ9.PbxkS3tkkjcMoWgOPcIwmcYeT_Vrujp0o3S8R9RofLA
@student-auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiTElCUkFSSUFOIiwic3ViIjoiTF9yYWhtYW4iLCJpYXQiOjE3NDE3NzUyODEsImV4cCI6MTc0MTg2MTY4MX0.ujo5GkxH9qNDYS2kumMbGS-jq0dCmfRLHRzy-t2SsDY

###
###
POST {{auth-url}}/register
Content-Type: application/json

{
    "username": "rahman",
    "password": "rahman",
    "email":"malcolmmarvin@chefalicious.com",
    "librarianId":101
}
### Forgot password
POST http://localhost:8080/auth/forgot-password?email=malcolmmarvin@chefalicious.com
###
POST http://127.0.0.1:8080/auth/reset-password 
Content-Type: application/json

{"token":"05986cca-af5d-4606-af56-70d838a956d9", "newPassword":"rahmanrocks"}
###
POST {{auth-url}}/authenticate
Content-Type: application/json

{
    "username": "rahman",
    "password": "rahman"
}
######
GET {{librarian-url}}
Authorization: Bearer {{auth-token}}
###
### BOOK
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567880",
    "title": "Prochur Koshto I",
    "quantity": 4,
    "price": 29.99,
    "coverLink": "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSWTwShHrDMcWf36xV2-WtIPcZ3mmckPyzkTQ&s",
    "categories": ["Horror", "Romance"],
    "authors": ["Monsur", "Atik"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567892",
    "title": "Britha",
    "quantity": 1,
    "price": 19.99,
    "coverLink":"https://m.media-amazon.com/images/I/51ZClf6ApnL._SL500_.jpg",
    "categories": ["Romance", "Thriller"],
    "authors": ["Arnil", "Saikat"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "6677889900",
    "title": "To Kill a Mockingbird",
    "quantity": 5,
    "price": 10.99,
    "coverLink": "https://media.glamour.com/photos/56e1f3c562b398fa64cbd310/master/w_1600%2Cc_limit/entertainment-2016-02-07-main.jpg",
    "categories": ["Classic", "Drama"],
    "authors": ["Harper", "Lee"]
}
###
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
        "isbn": "1122334455",
        "title": "The Great Gatsby",
        "quantity": 2,
        "price": 15.99,
        "coverLink": "https://i.pinimg.com/736x/9f/6f/81/9f6f81ec648dcbdf6691f2f590bd2b5b.jpg",
        "categories": ["Classic", "Novel"],
        "authors": ["F. Scott", "Fitzgerald"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "9876543210",
    "title": "The Lost World",
    "quantity": 3,
    "price": 25.99,
    "coverLink": "https://m.media-amazon.com/images/I/81YKkTLw6LL._AC_UF894,1000_QL80_.jpg",
    "categories": ["Adventure", "Sci-Fi"],
    "authors": ["John", "Doe"]
}
###
POST  {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567890",
    "title": "Prochur Koshto II",
    "quantity": 2,
    "price": 39.99,
    "coverLink": "https://mir-s3-cdn-cf.behance.net/projects/404/75f31f96918231.Y3JvcCwxMTc0LDkxOCwwLDE1OQ.png",
    "categories": ["Fantasy", "Action"],
    "authors": ["Monsur", "Mirsil"]
}
###
GET {{book-url}}?pageSize=5&page=0&sortBy=quantity&dir=desc
Authorization: Bearer {{auth-token}}
###
GET {{book-url}}/1234567890
Authorization: Bearer {{auth-token}}

### REVIEWING BOOKSREQUESTS
GET {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
### 
GET {{bookrequest-url}}/librarian/101
Authorization: Bearer {{auth-token}}
###  REJECTING BOOK REQUEST
PUT {{bookrequest-url}}/1/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{ "approveStatus":"REJECTED"
}
###  APPROVING BOOK REQUEST
PUT {{bookrequest-url}}/1/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus":"APPROVED"
}
###
PUT {{bookrequest-url}}/2/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus":"APPROVED"
}
###
PUT {{bookrequest-url}}/52/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus":"APPROVED"
}
###
GET {{borrow-url}}
Authorization: Bearer {{auth-token}}
###
PATCH  {{borrow-url}}/1/test-return
Authorization: Bearer {{auth-token}}
###
PATCH  {{borrow-url}}/2/test-return?delay=10
Authorization: Bearer {{auth-token}}