@auth-url=http://127.0.0.1:8080/librarian-auth
@librarian-url=http://127.0.0.1:8080/librarians
@book-url=http://localhost:8080/books 
@bookrequest-url=http://127.0.0.1:8080/bookrequests
@auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiTElCUkFSSUFOIiwic3ViIjoiTF9yYWhtYW4iLCJpYXQiOjE3Mzg0MjY0MTMsImV4cCI6MTczODUxMjgxM30.1d3nALtEp9wqFYMo-VFznur4OhzCYax3_bgHvvbK17s
@student-auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1RVREVOVCIsInN1YiI6IlNfbm9vciIsImlhdCI6MTczODQwMzUwOSwiZXhwIjoxNzM4NDg5OTA5fQ.Vef5K7UuTo2EQ0OTl43_hiBIcl-PFlIhWyGlIVFj2JU

###
###
POST {{auth-url}}/register
Content-Type: application/json

{
    "username": "rahman",
    "password": "rahman",
    "librarianId":101
}
###
###
POST {{auth-url}}/authenticate
Content-Type: application/json

{
    "username": "emily",
    "password": "emlem"
}
######
GET {{librarian-url}}
Authorization: Bearer {{auth-token}}
###
### BOOK
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567880",
    "title": "Prochur Koshto I",
    "quantity": 4,
    "price": 29.99,
    "coverLink": "http://dummylink9.com",
    "categories": ["Horror", "Romance"],
    "authors": ["Monsur", "Atik"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567892",
    "title": "Britha",
    "quantity": 1,
    "price": 19.99,
    "coverLink": "http://aummylink2.com",
    "categories": ["Romance", "Thriller"],
    "authors": ["Arnil", "Saikat"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "6677889900",
    "title": "To Kill a Mockingbird",
    "quantity": 5,
    "price": 10.99,
    "coverLink": "http://dummylink3.com",
    "categories": ["Classic", "Drama"],
    "authors": ["Harper", "Lee"]
}
###
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
        "isbn": "1122334455",
        "title": "The Great Gatsby",
        "quantity": 2,
        "price": 15.99,
        "coverLink": "http://dummylink2.com",
        "categories": ["Classic", "Novel"],
        "authors": ["F. Scott", "Fitzgerald"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "9876543210",
    "title": "The Lost World",
    "quantity": 3,
    "price": 25.99,
    "coverLink": "http://dummylink1.com",
    "categories": ["Adventure", "Sci-Fi"],
    "authors": ["John", "Doe"]
}
###
POST  {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567890",
    "title": "Prochur Koshto II",
    "quantity": 2,
    "price": 39.99,
    "coverLink": "http://dummylink2.com",
    "categories": ["Fantasy", "Action"],
    "authors": ["Monsur", "Mirsil"]
}
###
GET {{book-url}}
Authorization: Bearer {{student-auth-token}}

### REVIEWING BOOKSREQUESTS
GET {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
### 
GET {{bookrequest-url}}/1
Authorization: Bearer {{auth-token}}
###  REJECTING BOOK REQUEST
PUT {{bookrequest-url}}/1/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus":"REJECTED"
}
###  APPROVING BOOK REQUEST
PUT {{bookrequest-url}}/1/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus":"APPROVED"
}
###
PUT {{bookrequest-url}}/2/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus":"APPROVED"
}