@auth-url=http://127.0.0.1:8080/librarian-auth
@librarian-url=http://127.0.0.1:8080/librarians
@book-url=http://localhost:8080/books 
@auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiTElCUkFSSUFOIiwic3ViIjoiTF9lbWlseSIsImlhdCI6MTcxMzc5MDUyOCwiZXhwIjoxNzEzNzkxOTY4fQ.h9yuR5lC7jiDDJlpd1FfMhR2Gji1wNq-WQcwKDRRxCY

###
###
POST {{auth-url}}/register
Content-Type: application/json

{
    "username": "emily",
    "password": "emlem",
    "librarianId":101
}
###
###
POST {{auth-url}}/authenticate
Content-Type: application/json

{
    "username": "emily",
    "password": "emlem"
}
######
GET {{librarian-url}}
Authorization: Bearer {{auth-token}}
###
### BOOK
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567880",
    "title": "Prochur Koshto I",
    "quantity": 4,
    "price": 29.99,
    "coverLink": "http://dummylink9.com",
    "categories": ["Horror", "Romance"],
    "authors": ["Monsur", "Atik"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567892",
    "title": "Britha",
    "quantity": 1,
    "price": 19.99,
    "coverLink": "http://aummylink2.com",
    "categories": ["Romance", "Thriller"],
    "authors": ["Arnil", "Saikat"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "6677889900",
    "title": "To Kill a Mockingbird",
    "quantity": 5,
    "price": 10.99,
    "coverLink": "http://dummylink3.com",
    "categories": ["Classic", "Drama"],
    "authors": ["Harper", "Lee"]
}
###
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
        "isbn": "1122334455",
        "title": "The Great Gatsby",
        "quantity": 2,
        "price": 15.99,
        "coverLink": "http://dummylink2.com",
        "categories": ["Classic", "Novel"],
        "authors": ["F. Scott", "Fitzgerald"]
}
###
POST {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "9876543210",
    "title": "The Lost World",
    "quantity": 3,
    "price": 25.99,
    "coverLink": "http://dummylink1.com",
    "categories": ["Adventure", "Sci-Fi"],
    "authors": ["John", "Doe"]
}
###
POST  {{book-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567890",
    "title": "Prochur Koshto II",
    "quantity": 2,
    "price": 39.99,
    "coverLink": "http://dummylink2.com",
    "categories": ["Fantasy", "Action"],
    "authors": ["Monsur", "Mirsil"]
}