@student-url = http://127.0.0.1:8080/students
@bookrequest-url=http://127.0.0.1:8080/bookrequests

@borrowrecord-url=http://127.0.0.1:8080/borrowrecords

@book-url=http://localhost:8080/books/ 

@auth-url=http://127.0.0.1:8080/student-auth

@auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1RVREVOVCIsInN1YiI6IlNfbm9vciIsImlhdCI6MTczODQwMzUwOSwiZXhwIjoxNzM4NDg5OTA5fQ.Vef5K7UuTo2EQ0OTl43_hiBIcl-PFlIhWyGlIVFj2JU
###
POST {{auth-url}}/register
Content-Type: application/json

{
    "username": "noor",
    "password": "noor",
    "studentId":20101494
}
###
###
POST {{auth-url}}/authenticate
Content-Type: application/json

{
    "username": "ashen",
    "password": "ashen"
}
###
GET {{book-url}}/1234567890
###
GET {{book-url}}
### STUDENT

POST {{student-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "username": "britt",
    "password": "brt",
    "studentId":20101320
}

###
POST {{student-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "username": "ash",
    "password": "ashen",
    "studentId":20101498
}
###
GET {{student-url}}
Authorization: Bearer {{auth-token}}
###
GET {{student-url}}/20101498
###
PUT {{student-url}}/20101320
Content-Type: application/json

{
    "password": "brot"
}
###
DELETE {{student-url}}/20101320
###