@student-url = http://127.0.0.1:8080/students
@bookrequest-url=http://127.0.0.1:8080/bookrequests

@borrowrecord-url=http://127.0.0.1:8080/borrowrecords

@book-url=http://localhost:8080/books/ 

@auth-url=http://127.0.0.1:8080/student-auth

@auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiU1RVREVOVCIsInN1YiI6IlNfbm9vciIsImlhdCI6MTczODQyNjQyOCwiZXhwIjoxNzM4NTEyODI4fQ.eo1gXOuvm6_fm0b7TEjZeYAPOjwakw9Avn4G4L3GCsw
###
POST {{auth-url}}/register
Content-Type: application/json

{
    "username": "noor",
    "password": "noor",
    "studentId":20101494
}
###
###
POST {{auth-url}}/authenticate
Content-Type: application/json

{
    "username": "ashen",
    "password": "ashen"
}
###
GET {{book-url}}/1234567890
###
GET {{book-url}}
### STUDENT

POST {{student-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "username": "britt",
    "password": "brt",
    "studentId":20101320
}

###
POST {{student-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "username": "ash",
    "password": "ashen",
    "studentId":20101498
}
###
GET {{student-url}}
Authorization: Bearer {{auth-token}}
###
GET {{student-url}}/20101498
###
PUT {{student-url}}/20101320
Content-Type: application/json

{
    "password": "brot"
}
###
DELETE {{student-url}}/20101320
### REQUESTING BOOKS
POST {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "9876543210",
    "librarianId":101,
    "studentId":20101494

}
###
POST {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn":"6677889900",
    "librarianId":101,
    "studentId":20101494

}
### 
GET {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
### 
GET {{bookrequest-url}}/2
Authorization: Bearer {{auth-token}}

### BORROW-RECORDS 
POST {{borrowrecord-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "9876543210",
    "studentId":20101494,
    "bookRequestId":1

}
### 
POST {{borrowrecord-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn":"6677889900",
    "studentId":20101494,
    "bookRequestId":2

}

###
GET {{borrowrecord-url}}
Authorization: Bearer {{auth-token}}
### 
GET {{borrowrecord-url}}/1
Authorization: Bearer {{auth-token}}

### RETURNING BOOKS
PUT {{borrowrecord-url}}/252/return
Authorization: Bearer {{auth-token}}
###
PUT {{borrowrecord-url}}/253/return
Authorization: Bearer {{auth-token}}

### CHECKING DELAY FINES
PUT {{borrowrecord-url}}/252/fine
Authorization: Bearer {{auth-token}}
### 
PUT {{borrowrecord-url}}/253/fine
Authorization: Bearer {{auth-token}}

### CHECKING FINES WITH BOOKLOST
PUT {{borrowrecord-url}}/252/booklost
Authorization: Bearer {{auth-token}}
### 
PUT {{borrowrecord-url}}/252/fine
Authorization: Bearer {{auth-token}}
### 
PUT {{borrowrecord-url}}/253/booklost
Authorization: Bearer {{auth-token}}
### 
PUT {{borrowrecord-url}}/253/fine
Authorization: Bearer {{auth-token}}
### 