### /usr/bin/env /usr/lib/jvm/java-17-openjdk-amd64/bin/java @/tmp/cp_ejz6d0trlumqqaelmb68ohehf.argfile com.eshan.library.LibraryApplication > log.txt 
@admin-url = http://127.0.0.1:8080/admins
@librarianinfo-url =http://127.0.0.1:8080/librarianinfo 
@librarian-url = http://127.0.0.1:8080/librarians
@student-url = http://127.0.0.1:8080/students
@bookrequest-url=http://127.0.0.1:8080/bookrequests

@borrowrecord-url=http://127.0.0.1:8080/borrowrecords

@auth-url=http://127.0.0.1:8080/auth
@sauth-url=http://127.0.0.1:8080/student-auth

@auth-token=eyJhbGciOiJIUzI1NiJ9.eyJyb2xlIjoiQURNSU4iLCJzdWIiOiJBX21laHJhYiIsImlhdCI6MTcxMzc5MDQ5NiwiZXhwIjoxNzEzNzkxOTM2fQ.ngTgW54j-dj-1SAMXx25ZoY0sdEChpE-STaPysG7AQ4

###
POST {{auth-url}}/register
Content-Type: application/json

{
    "username": "mehrab",
    "password": "admin"
}
###
POST {{auth-url}}/authenticate
Content-Type: application/json

{
    "username": "mehrab",
    "password": "admin"
}

###
POST {{admin-url}}
Content-Type: application/json

{
    "username": "mehrab",
    "password": "admin"
}
###
PUT {{admin-url}}/1
Content-Type: application/json

{
    "username": "eshan",
    "password": "123admin"
}


###
GET {{admin-url}}
Authorization: Bearer {{auth-token}}
###
@studentinfo-url=http://127.0.0.1:8080/studentinfo
###
POST {{studentinfo-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "name": "Ash",
    "email": "ashley@gmail.com",
    "admin":{
        "id":1
    },
    "id":20101498

}
###
POST {{studentinfo-url}}
Content-Type: application/json
Authorization: Bearer {{auth-token}}

{
    "name": "britt",
    "email": "britany@gmail.com",
    "admin":{
        "id":1
    },
    "id":20101320
}
###
GET {{studentinfo-url}}
Authorization: Bearer {{auth-token}}
###
PUT {{studentinfo-url}}/email/20101320
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "name": "Britt",
    "email": "brittany@gmail.com"
}
###
PUT {{studentinfo-url}}/name/2010
Content-Type: application/json

{
    "name": "Britt",
    "email": "britany@gmail.com",
    "admin":{
        "id":1
    },
    "id":2010
}
###
DELETE {{studentinfo-url}}/20101320
###
POST {{librarianinfo-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "name": "Emily",
    "email": "em@gmail.com",
    "admin":{
        "id":1
    },
    "id":101

}
###
POST {{librarianinfo-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "name": "Brad",
    "email": "br@gmail.com",
    "admin":{
        "id":1
    },
    "id":102
}
###
GET {{librarianinfo-url}}
Authorization: Bearer {{auth-token}}
###
GET {{librarianinfo-url}}/101
Authorization: Bearer {{auth-token}}
###
PUT {{librarianinfo-url}}/email/102
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "email": "brad@gmail.com"
}
###
PUT {{librarianinfo-url}}/name/102
Content-Type: application/json

{
    "name": "Brady"
}
###
DELETE {{librarianinfo-url}}/102
Authorization: Bearer {{auth-token}}
###

POST {{librarian-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "username": "emily",
    "password": "ema",
    "librarianId":101
}

###
POST {{librarian-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "username": "brad",
    "password": "brad",
    "librarianId":102
}
###
GET {{librarian-url}}
Authorization: Bearer {{auth-token}}
###
GET {{librarian-url}}/101
Authorization: Bearer {{auth-token}}
###
PUT {{librarian-url}}/102
Content-Type: application/json

{
    "password": "brady"
}
###
DELETE {{librarian-url}}/101
Authorization: Bearer {{auth-token}}

### BOOK


POST http://localhost:8080/books 
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567890",
    "title": "Prochur Koshto II",
    "quantity": 2,
    "price": 39.99,
    "coverLink": "http://dummylink2.com",
    "categories": ["Fantasy", "Action"],
    "authors": ["Monsur", "Mirsil"]
}
###
GET http://localhost:8080/books/1234567890 
Authorization: Bearer {{auth-token}}
###
GET http://localhost:8080/books 
Authorization: Bearer {{auth-token}}


###
DELETE http://localhost:8080/books/1234567890 HTTP/1.1
Authorization: Bearer {{auth-token}}

###
PUT http://localhost:8080/books/1234567890/quantity HTTP/1.1
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "quantity": 5
}

###
PUT http://localhost:8080/books/1234567890/coverlink HTTP/1.1
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "coverLink": "http://newdummylink.com"
}

### BOOK REQUESTS
POST  {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "isbn": "1234567890",
    "studentId":20101498,
    "librarianId":101
}

###
GET {{bookrequest-url}}
Authorization: Bearer {{auth-token}}
###
PUT {{bookrequest-url}}/1/status
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "approveStatus": "APPROVED"
}

###
### BORROW RECORDS
POST  {{borrowrecord-url}}
Authorization: Bearer {{auth-token}}
Content-Type: application/json

{
    "bookId": 1,
    "studentId":20101498,
    "bookRequestId":1
}

###
GET {{borrowrecord-url}}
Authorization: Bearer {{auth-token}}
###