spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library_management
    username: your-database-username
    password: your-database-password
    driver-class-name: com.mysql.jdbc.Driver
  mvc:
    enableLoggingRequestDetails: false
  jpa:
    open-in-view: true
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: false

server:
  port: 8080

logging:
  pattern:
    console: "%d{HH:mm:ss dd-MM-yyyy} - %msg%n"
    file: "%d{HH:mm:ss dd-MM-yyyy} - %msg%n"
  file:
    name: app.log
  level:
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    com.eshan.library: DEBUG

postmark:
  api-key: your-postmark-api-key
  from-email: no-reply@yourdomain.com # should be configured in postmark
