spring:
  datasource:
    url: jdbc:mysql://127.0.0.1:3306/library_management
    username: root
    password: rootpassword
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    hibernate:
      ddl-auto: create-drop
    database: mysql
    show-sql: false
server:
  port: 8080
  error:
    include-stacktrace: never
logging:
  pattern:
    console: "%d{HH:mm:ss dd-MM-yyyy} - %msg%n"
    file: "%d{HH:mm:ss dd-MM-yyyy} - %msg%n"
  file:
    name: app.log
  level: 
    org.springframework.security: TRACE
    org.springframework.web: DEBUG
    com.eshan.library: DEBUG